### ISSUE TITLE
Not loading on Ubuntu 15.10

### ISSUE THREAD

**Issue by rirze** [sebglazebrook/aliases#11]
Hi, after installing the deb file in the repository, I created a simple .aliases file in a directory. I could see the alias by running `aliases` and `aliases list` but it did not seem like the alias was actually loaded into the environment even after running `aliases rehash`. I can run the command by typing `aliases exec . "cmd"` but this is inconvenient and not the default behavior, I assume. Is there anything I'm missing or need to run in order to fix this and get default behavior?

**Comment by sebglazebrook** [comment]
Hey,

You need to run `aliases init` inside the directory where you `.aliases` file is.

If you run `aliases init` and there is no `.aliases` file it will create one for you.

Then after running `aliases rehash` they should be available.

You can see all initialised directories by looking in the config file:

`cat ~/.aliases_cfg`

Hope this helps.

**Comment by sebglazebrook** [comment]
Also I forgot to mention you have to add the aliases to your path. You can do this by running

`aliases init --global` and putting that in your bashrc or somewhere similar.

**Comment by sebglazebrook** [comment]
Closing this. Will reopen if I hear back from you @rirze
