### ISSUE TITLE
executing alias gives "bash: command not found"

### ISSUE THREAD

**Issue by jedi-tester** [sebglazebrook/aliases#43]
Hi,

Trying to add some simple aliases with your plugin.
1. `$cd ~ && aliases init`
2. `$vim .aliases`
3. added 
```
la: 
  command: ls -la
```
to .aliases file
4. `$aliases rehash`
5. `$la`

Getting: `-bash: alias: la: not found`
Only way I could execute the alias is with `$aliases exec . la`
Am I doing something wrong or?

**Comment by sebglazebrook** [comment]
Hi,

Thanks for raising the issue.

It'll most likely be that the alias shims are not included in the $PATH.

To add it to your path, add the following to a file that gets loaded on the initialization of the terminal, say `~/.bashrc`

```
eval "$(aliases init --global)"
```

Now when you reload the shell or `source ~/.bashrc` your $PATH should include `~/.aliases.d/shims` and your alias `la` should be there.

You can double check the location by running `type -p la` it should return `~/.aliases.d/shims/la`

For reference, what operating system are you using?

**Comment by jedi-tester** [comment]
Thanks @sebglazebrook, and sorry for late response. Looks to be working after adding `eval "$(aliases init --global)"` to my `~/.bash_profile`
Although the `type -p la` does not return anything, but typing `which la` does return `~/.aliases.d/shims/la`

I'm on MacOS Sierra

**Comment by gonzalo-bulnes** [comment]
Hi @sebglazebrook!

AS an additional data point: I'm using **aliases** v0.8.1 on MacOS Mojave (10.14.6) and got the same issue. The workaround works as well! 👍
