### ISSUE TITLE
Homebrew install warning

### ISSUE THREAD

**Issue by jonathanwren** [sebglazebrook/aliases#45]
Running `brew install sebglazebrook/aliases/aliases` results in the following warning: 

```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/sebglazebrook/homebrew-aliases/aliases.rb:21:in `caveats'
Please report this to the sebglazebrook/aliases tap!
```

Thought you might like to know.

**Comment by sebglazebrook** [comment]
Thanks heaps!

**Comment by omares** [comment]
Any plans to fix this? :)

**Comment by sebglazebrook** [comment]
Looks like this is already fixed @omares and @jonathanwren 

See here: https://github.com/sebglazebrook/homebrew-aliases/blob/master/aliases.rb#L16

Commit that fixed it is here: https://github.com/sebglazebrook/homebrew-aliases/commit/5572cfa9064c92f92ded5959e3c301c92502f1b0#diff-380849b21137d4d0d7b0e54b99fa32cf

Can you confirm  you have the latest brew package by doing a `brew update` and trying again.

If that doesn't work can you try tapping it first, I think it's `brew tap sebglazebrook/aliases` or `brew tap `sebglazebrook/aliases/aliases` and then try to `brew install sebglazebrook/aliases`. 

Sorry I don't have a Mac to test it on.

**Comment by jonathanwren** [comment]
I get this now: 

```
$ b install sebglazebrook/aliases/aliases
==> Installing aliases from sebglazebrook/aliases
==> Downloading https://github.com/sebglazebrook/aliases/raw/master/releases/0.8.1/mac/aliases.tar.gz
==> Downloading from https://raw.githubusercontent.com/sebglazebrook/aliases/master/releases/0.8.1/mac/aliases.tar.gz
######################################################################## 100.0%
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/sebglazebrook/homebrew-aliases/aliases.rb:21:in `caveats'
Please report this to the sebglazebrook/aliases tap!
Or, even better, submit a PR to fix it!
```

I guess it's just `<<~EOS` now. I'll send you a PR shortly.

**Comment by sebglazebrook** [comment]
Thanks. Just merged your PR

**Comment by jonathanwren** [comment]
And confirmed that I can now install Aliases from Homebrew without any warnings or errors. 

```
$ brew install aliases
==> Installing aliases from sebglazebrook/aliases
==> Downloading https://github.com/sebglazebrook/aliases/raw/master/releases/0.8.1/mac/aliases.tar.gz
==> Downloading from https://raw.githubusercontent.com/sebglazebrook/aliases/master/releases/0.8.1/mac/aliases.tar.gz
######################################################################## 100.0%
==> Caveats
To activate the alias shims add the following to your profile:

  echo 'eval "$(aliases init --global)"' >> ~/.bash_profile

==> Summary
🍺  /usr/local/Cellar/aliases/0.8.1: 3 files, 2.8MB, built in 2 seconds
```
