### ISSUE TITLE
aliases not recognized

### ISSUE THREAD

**Issue by patrikalienus** [sebglazebrook/aliases#60]
I'm on Mac OS Monterey
GNU bash, version 5.1.12(1)-release (x86_64-apple-darwin19.6.0)

```
$ aliases

ALIAS  COMMAND                      CONFIRM
build  npm run build                false
debug  grc tail -f ../../debug.log  false
dev    npm run dev                  false

$ dev
bash: dev: command does not exist
```

Clearly, aliases is installed and working properly, until I actually wanna execute an alias.
I've been scratching my head for the better part of an hour trying to figure this out and I can't make sense of it. It works just fine on my laptop - also a Mac running Monterey.

Anyone else have this issue?

**Comment by sebglazebrook** [comment]
Sorry I haven't been active on github for a while. 
This should get you going https://github.com/sebglazebrook/aliases/issues/57#issuecomment-593412999

**Comment by patrikalienus** [comment]
@sebglazebrook Awesome, I'll have a look when I'm back on the computer the issue is on and will report back :)
