### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by seenukarthi** [sebglazebrook/aliases#63]
This project has been inactive since Dec 2018. Is this project still alive?

**Comment by patrikalienus** [comment]
Sadly, it looks stale. Which is a shame because I've gotten really used to using it and now that I've been forced over the ARM on the new Macbook, I can't use this anymore as there's no support for ARM. And I'm not knowledgeable enough to make it work on ARM either.

**Comment by seenukarthi** [comment]
> Sadly, it looks stale. Which is a shame because I've gotten really used to using it and now that I've been forced over the ARM on the new Macbook, I can't use this anymore as there's no support for ARM. And I'm not knowledgeable enough to make it work on ARM either.

Doesn't rosetta 2 handle this?

**Comment by patrikalienus** [comment]
Possible, but I don't know how to get it working. I've only been on ARM for a few weeks so haven't had time to dig into it.

**Comment by sebglazebrook** [comment]
Hi! 

Sorry I don't check in here that often any more. The project in one way is still alive. I and others still use it daily but I don't regularly update it and am more than happy for people to create pull requests. I use it on both a mac and linux (debian) machine currently without issues. 

What's the issue you're seeing?

**Comment by patrikalienus** [comment]
Interestingly enough, it just started working a few weeks ago. I can't remember the exact issue, but I deduced that it was due to the CPU architecture. However it's working now so.. yay :)

**Comment by choman** [comment]
Anyone know of a GOOD  alternative for this project?

**Comment by sebglazebrook** [comment]
what issue are you seeing @choman ?

I've had a little more time of recent so I can look into any issues you might have.

**Comment by sebglazebrook** [comment]
Closing but happy to reopen and I'll aim to keep a better eye on things
